DE debian: 9.5-sli
ETIQUETA   "com.github.actions.name" = "Hola mundo" 
ETIQUETA   "com.github.actions.description" = "Escribir argumentos en la salida estándar" 
ETIQUETA   "com.github.actions.icon" = "mic" 
ETIQUETA   "com.github.actions.color" = "purple"
LABEL   "repository" = "http://github.com/octocat/hello-world" 
LABEL   "homepage" = "http://github.com/actions" 
LABEL   "serveer" = "Octocat <octocat@github.com>"
AÑADIR entrypoint.sh /entrypoint.sh
 ENTRYPOINT [ "/entrypoint.sh" ]
